///////////////////////////////////////////////////////////////////
// generated by ./generate_service_name.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>

#pragma once

extern NSString const *const BrainCloudServiceNameNone;
extern NSString const *const BrainCloudServiceNameAppStore;
extern NSString const *const BrainCloudServiceNameAuthenticate;
extern NSString const *const BrainCloudServiceNameAuthenticateV2;
extern NSString const *const BrainCloudServiceNameIdentity;
extern NSString const *const BrainCloudServiceNameCurrency;
extern NSString const *const BrainCloudServiceNameFriendData;
extern NSString const *const BrainCloudServiceNameHeartBeat;
extern NSString const *const BrainCloudServiceNameServerTime;
extern NSString const *const BrainCloudServiceNamePushNotification;
extern NSString const *const BrainCloudServiceNameGlobalGameStatistics;
extern NSString const *const BrainCloudServiceNamePlayerStatisticsEvent;
extern NSString const *const BrainCloudServiceNameTwitter;
extern NSString const *const BrainCloudServiceNameSteam;
extern NSString const *const BrainCloudServiceNamePlayerState;
extern NSString const *const BrainCloudServiceNameEntity;
extern NSString const *const BrainCloudServiceNameGlobalEntity;
extern NSString const *const BrainCloudServiceNameFriend;
extern NSString const *const BrainCloudServiceNameTime;
extern NSString const *const BrainCloudServiceNameSocialLeaderboard;
extern NSString const *const BrainCloudServiceNameEvent;
extern NSString const *const BrainCloudServiceNameProduct;
extern NSString const *const BrainCloudServiceNamePlayerStatistics;
extern NSString const *const BrainCloudServiceNameGlobalStatistics;
extern NSString const *const BrainCloudServiceNameAsyncMatch;
extern NSString const *const BrainCloudServiceNameScript;
extern NSString const *const BrainCloudServiceNameMatchMaking;
extern NSString const *const BrainCloudServiceNameOneWayMatch;
extern NSString const *const BrainCloudServiceNamePlaybackStream;
extern NSString const *const BrainCloudServiceNameGamification;
extern NSString const *const BrainCloudServiceNameGlobalApp;
extern NSString const *const BrainCloudServiceNameS3Handling;
extern NSString const *const BrainCloudServiceNameRedemptionCode;
extern NSString const *const BrainCloudServiceNameDataStream;
extern NSString const *const BrainCloudServiceNameProfanity;
extern NSString const *const BrainCloudServiceNameFile;
extern NSString const *const BrainCloudServiceNameVirtualCurrency;
