///////////////////////////////////////////////////////////////////
// generated by ./generate_service_name.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#import "ServiceName.hh"
#import "braincloud/ServiceName.h"

NSString const *const BrainCloudServiceNameNone = [NSString stringWithCString:BrainCloud::ServiceName::None.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameAuthenticate = [NSString stringWithCString:BrainCloud::ServiceName::Authenticate.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameAuthenticateV2 = [NSString stringWithCString:BrainCloud::ServiceName::AuthenticateV2.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameIdentity = [NSString stringWithCString:BrainCloud::ServiceName::Identity.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameCurrency = [NSString stringWithCString:BrainCloud::ServiceName::Currency.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameFriendData = [NSString stringWithCString:BrainCloud::ServiceName::FriendData.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameHeartBeat = [NSString stringWithCString:BrainCloud::ServiceName::HeartBeat.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameServerTime = [NSString stringWithCString:BrainCloud::ServiceName::ServerTime.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNamePushNotification = [NSString stringWithCString:BrainCloud::ServiceName::PushNotification.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameGlobalGameStatistics = [NSString stringWithCString:BrainCloud::ServiceName::GlobalGameStatistics.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNamePlayerStatisticsEvent = [NSString stringWithCString:BrainCloud::ServiceName::PlayerStatisticsEvent.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameTwitter = [NSString stringWithCString:BrainCloud::ServiceName::Twitter.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameSteam = [NSString stringWithCString:BrainCloud::ServiceName::Steam.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNamePlayerState = [NSString stringWithCString:BrainCloud::ServiceName::PlayerState.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameEntity = [NSString stringWithCString:BrainCloud::ServiceName::Entity.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameGlobalEntity = [NSString stringWithCString:BrainCloud::ServiceName::GlobalEntity.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameFriend = [NSString stringWithCString:BrainCloud::ServiceName::Friend.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameTime = [NSString stringWithCString:BrainCloud::ServiceName::Time.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameSocialLeaderboard = [NSString stringWithCString:BrainCloud::ServiceName::SocialLeaderboard.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameEvent = [NSString stringWithCString:BrainCloud::ServiceName::Event.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameProduct = [NSString stringWithCString:BrainCloud::ServiceName::Product.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNamePlayerStatistics = [NSString stringWithCString:BrainCloud::ServiceName::PlayerStatistics.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameGlobalStatistics = [NSString stringWithCString:BrainCloud::ServiceName::GlobalStatistics.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameAsyncMatch = [NSString stringWithCString:BrainCloud::ServiceName::AsyncMatch.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameScript = [NSString stringWithCString:BrainCloud::ServiceName::Script.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameMatchMaking = [NSString stringWithCString:BrainCloud::ServiceName::MatchMaking.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameOneWayMatch = [NSString stringWithCString:BrainCloud::ServiceName::OneWayMatch.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNamePlaybackStream = [NSString stringWithCString:BrainCloud::ServiceName::PlaybackStream.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameGamification = [NSString stringWithCString:BrainCloud::ServiceName::Gamification.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameGlobalApp = [NSString stringWithCString:BrainCloud::ServiceName::GlobalApp.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameS3Handling = [NSString stringWithCString:BrainCloud::ServiceName::S3Handling.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameRedemptionCode = [NSString stringWithCString:BrainCloud::ServiceName::RedemptionCode.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameDataStream = [NSString stringWithCString:BrainCloud::ServiceName::DataStream.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameProfanity = [NSString stringWithCString:BrainCloud::ServiceName::Profanity.getValue().c_str() encoding:NSASCIIStringEncoding];
NSString const *const BrainCloudServiceNameFile = [NSString stringWithCString:BrainCloud::ServiceName::File.getValue().c_str() encoding:NSASCIIStringEncoding];
