///////////////////////////////////////////////////////////////////
// generated by ./generate_status_codes.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>

#pragma once

extern const NSInteger HTTP_ACCEPTED;
extern const NSInteger HTTP_BAD_GATEWAY;
extern const NSInteger HTTP_BAD_METHOD;
extern const NSInteger HTTP_BAD_REQUEST;
extern const NSInteger HTTP_CLIENT_TIMEOUT;
extern const NSInteger HTTP_CONFLICT;
extern const NSInteger HTTP_CREATED;
extern const NSInteger HTTP_ENTITY_TOO_LARGE;
extern const NSInteger HTTP_FORBIDDEN;
extern const NSInteger HTTP_GATEWAY_TIMEOUT;
extern const NSInteger HTTP_GONE;
extern const NSInteger HTTP_INTERNAL_ERROR;
extern const NSInteger HTTP_LENGTH_REQUIRED;
extern const NSInteger HTTP_MOVED_PERM;
extern const NSInteger HTTP_MOVED_TEMP;
extern const NSInteger HTTP_MULT_CHOICE;
extern const NSInteger HTTP_NO_CONTENT;
extern const NSInteger HTTP_NOT_ACCEPTABLE;
extern const NSInteger HTTP_NOT_AUTHORITATIVE;
extern const NSInteger HTTP_NOT_FOUND;
extern const NSInteger HTTP_NOT_IMPLEMENTED;
extern const NSInteger HTTP_NOT_MODIFIED;
extern const NSInteger HTTP_OK;
extern const NSInteger HTTP_PARTIAL;
extern const NSInteger HTTP_PAYMENT_REQUIRED;
extern const NSInteger HTTP_PRECON_FAILED;
extern const NSInteger HTTP_PROXY_AUTH;
extern const NSInteger HTTP_REQ_TOO_LONG;
extern const NSInteger HTTP_RESET;
extern const NSInteger HTTP_SEE_OTHER;
extern const NSInteger HTTP_SERVER_ERROR;
extern const NSInteger HTTP_UNAUTHORIZED;
extern const NSInteger HTTP_UNAVAILABLE;
extern const NSInteger HTTP_UNSUPPORTED_TYPE;
extern const NSInteger HTTP_USE_PROXY;
extern const NSInteger HTTP_VERSION;
extern const NSInteger HTTP_CUSTOM;
extern const NSInteger HTTP_CLIENT_NETWORK_ERROR;

