///////////////////////////////////////////////////////////////////
// generated by ./generate_status_codes.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>

#pragma once

extern const int HTTP_ACCEPTED;
extern const int HTTP_BAD_GATEWAY;
extern const int HTTP_BAD_METHOD;
extern const int HTTP_BAD_REQUEST;
extern const int HTTP_CLIENT_TIMEOUT;
extern const int HTTP_CONFLICT;
extern const int HTTP_CREATED;
extern const int HTTP_ENTITY_TOO_LARGE;
extern const int HTTP_FORBIDDEN;
extern const int HTTP_GATEWAY_TIMEOUT;
extern const int HTTP_GONE;
extern const int HTTP_INTERNAL_ERROR;
extern const int HTTP_LENGTH_REQUIRED;
extern const int HTTP_MOVED_PERM;
extern const int HTTP_MOVED_TEMP;
extern const int HTTP_MULT_CHOICE;
extern const int HTTP_NO_CONTENT;
extern const int HTTP_NOT_ACCEPTABLE;
extern const int HTTP_NOT_AUTHORITATIVE;
extern const int HTTP_NOT_FOUND;
extern const int HTTP_NOT_IMPLEMENTED;
extern const int HTTP_NOT_MODIFIED;
extern const int HTTP_OK;
extern const int HTTP_PARTIAL;
extern const int HTTP_PAYMENT_REQUIRED;
extern const int HTTP_PRECON_FAILED;
extern const int HTTP_PROXY_AUTH;
extern const int HTTP_REQ_TOO_LONG;
extern const int HTTP_RESET;
extern const int HTTP_SEE_OTHER;
extern const int HTTP_SERVER_ERROR;
extern const int HTTP_UNAUTHORIZED;
extern const int HTTP_UNAVAILABLE;
extern const int HTTP_UNSUPPORTED_TYPE;
extern const int HTTP_USE_PROXY;
extern const int HTTP_VERSION;
extern const int HTTP_CUSTOM;
extern const int HTTP_CLIENT_NETWORK_ERROR;

