///////////////////////////////////////////////////////////////////
// generated by ./generate_status_codes.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#include "StatusCodes.hh"

const NSInteger HTTP_ACCEPTED = 202;			// HTTP Status-Code 202: Accepted.
const NSInteger HTTP_BAD_GATEWAY = 502;		// HTTP Status-Code 502: Bad Gateway.
const NSInteger HTTP_BAD_METHOD = 405;			// HTTP Status-Code 405: Method Not Allowed.
const NSInteger HTTP_BAD_REQUEST = 400;		// HTTP Status-Code 400: Bad Request.
const NSInteger HTTP_CLIENT_TIMEOUT = 408;		// HTTP Status-Code 408: Request Time-Out.
const NSInteger HTTP_CONFLICT = 409;			// HTTP Status-Code 409: Conflict.
const NSInteger HTTP_CREATED = 201;			// HTTP Status-Code 201: Created.
const NSInteger HTTP_ENTITY_TOO_LARGE = 413;	// HTTP Status-Code 413: Request Entity Too Large.
const NSInteger HTTP_FORBIDDEN = 403;			// HTTP Status-Code 403: Forbidden.
const NSInteger HTTP_GATEWAY_TIMEOUT = 504;	// HTTP Status-Code 504: Gateway Timeout.
const NSInteger HTTP_GONE = 410;				// HTTP Status-Code 410: Gone.
const NSInteger HTTP_INTERNAL_ERROR = 500;		// HTTP Status-Code 500: Internal Server Error.
const NSInteger HTTP_LENGTH_REQUIRED = 411;	// HTTP Status-Code 411: Length Required.
const NSInteger HTTP_MOVED_PERM = 301;			// HTTP Status-Code 301: Moved Permanently.
const NSInteger HTTP_MOVED_TEMP = 302;			// HTTP Status-Code 302: Temporary Redirect.
const NSInteger HTTP_MULT_CHOICE = 300;		// HTTP Status-Code 300: Multiple Choices.
const NSInteger HTTP_NO_CONTENT = 204;			// HTTP Status-Code 204: No Content.
const NSInteger HTTP_NOT_ACCEPTABLE = 406;		// HTTP Status-Code 406: Not Acceptable.
const NSInteger HTTP_NOT_AUTHORITATIVE = 203;	// HTTP Status-Code 203: Non-Authoritative Information.
const NSInteger HTTP_NOT_FOUND = 404;			// HTTP Status-Code 404: Not Found.
const NSInteger HTTP_NOT_IMPLEMENTED = 501;	// HTTP Status-Code 501: Not Implemented.
const NSInteger HTTP_NOT_MODIFIED = 304;		// HTTP Status-Code 304: Not Modified.
const NSInteger HTTP_OK = 200;					// HTTP Status-Code 200: OK.
const NSInteger HTTP_PARTIAL = 206;			// HTTP Status-Code 206: Partial Content.
const NSInteger HTTP_PAYMENT_REQUIRED = 402;	// HTTP Status-Code 402: Payment Required.
const NSInteger HTTP_PRECON_FAILED = 412;		// HTTP Status-Code 412: Precondition Failed.
const NSInteger HTTP_PROXY_AUTH = 407;			// HTTP Status-Code 407: Proxy Authentication Required.
const NSInteger HTTP_REQ_TOO_LONG = 414;		// HTTP Status-Code 414: Request-URI Too Large.
const NSInteger HTTP_RESET = 205;				// HTTP Status-Code 205: Reset Content.
const NSInteger HTTP_SEE_OTHER = 303;			// HTTP Status-Code 303: See Other.
const NSInteger HTTP_SERVER_ERROR = 500;		// Deprecated. it is misplaced and shouldn't have existed.
const NSInteger HTTP_UNAUTHORIZED = 401;		// HTTP Status-Code 401: Unauthorized.
const NSInteger HTTP_UNAVAILABLE = 503;		// HTTP Status-Code 503: Service Unavailable.
const NSInteger HTTP_UNSUPPORTED_TYPE = 415;	// HTTP Status-Code 415: Unsupported Media Type.
const NSInteger HTTP_USE_PROXY = 305;			// HTTP Status-Code 305: Use Proxy.
const NSInteger HTTP_VERSION = 505;			// HTTP Status-Code 505: HTTP Version Not Supported.
const NSInteger HTTP_CUSTOM = 900;
const NSInteger HTTP_CLIENT_NETWORK_ERROR= 900; // A custom status code raised internally by bc client
