#!/bin/bash

out_hh="../Shared/ServiceName.hh"
out_mm="../Shared/ServiceName.mm"
in_h="../../braincloud-cpp/Shared/ServiceName.h"
in_cpp="../../braincloud-cpp/Shared/ServiceName.cpp"

# build header
rm -rf "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "// generated by $0, do not edit manually!" >> "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "" >> "$out_hh"
echo "#import <Foundation/Foundation.h>" >> "$out_hh"
echo "" >> "$out_hh"
echo "#pragma once" >> "$out_hh"
echo "" >> "$out_hh"
sed -n -E "/.*static const ServiceName/{p;}" "$in_h" | sed -E "s/.*static const ServiceName (.*);/extern NSString const \*const BrainCloudServiceName\1;/g" >> "$out_hh"

# build source
rm -rf "$out_mm"
echo "///////////////////////////////////////////////////////////////////" >> "$out_mm"
echo "// generated by $0, do not edit manually!" >> "$out_mm"
echo "///////////////////////////////////////////////////////////////////" >> "$out_mm"
echo "" >> "$out_mm"
echo "#import \"ServiceName.hh\"" >> "$out_mm"
echo "#import \"ServiceName.h\"" >> "$out_mm"
echo "" >> "$out_mm"
sed -n -E "/.*static const ServiceName/{p;}" "$in_h" | sed -E "s/.*static const ServiceName (.*);/NSString const \*const BrainCloudServiceName\1 = \[NSString stringWithCString:BrainCloud::ServiceName::\1\.getValue\(\)\.c_str\(\) encoding:NSASCIIStringEncoding\];/g" >> "$out_mm"

