#!/bin/bash

out_hh="../Shared/ReasonCodes.hh"
out_mm="../Shared/ReasonCodes.m"
in_h="../../braincloud-cpp/Shared/reason_codes.h"
#in_cpp="../../braincloud-cpp/Shared/reason_codes.cpp"

# build header
rm -rf "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "// generated by $0, do not edit manually!" >> "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "" >> "$out_hh"
echo "#import <Foundation/Foundation.h>" >> "$out_hh"
echo "" >> "$out_hh"
echo "#pragma once" >> "$out_hh"
echo "" >> "$out_hh"
sed -n -E "/.*static const int/{p;}" "$in_h" | sed -E "s/.*const int ([A-Za-z0-9_]*).*$/extern const NSInteger \1;/g" >> "$out_hh"
echo "" >> "$out_hh"

# build source
rm -rf "$out_mm"
echo "///////////////////////////////////////////////////////////////////" >> "$out_mm"
echo "// generated by $0, do not edit manually!" >> "$out_mm"
echo "///////////////////////////////////////////////////////////////////" >> "$out_mm"
echo "" >> "$out_mm"
echo "#include \"ReasonCodes.hh\""  >> "$out_mm"
echo "" >> "$out_mm"
sed -n -E "/.*static const int/{p;}" "$in_h" | sed -E "s/.*const int (.*)$/const NSInteger \1/g" >> "$out_mm"

