#!/bin/bash

out_hh="../Shared/StatusCodes.hh"
in_h="../../braincloud-cpp/Shared/http_codes.h"

# build header
rm -rf "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "// generated by $0, do not edit manually!" >> "$out_hh"
echo "///////////////////////////////////////////////////////////////////" >> "$out_hh"
echo "" >> "$out_hh"
echo "#import <Foundation/Foundation.h>" >> "$out_hh"
echo "" >> "$out_hh"
echo "#pragma once" >> "$out_hh"
echo "" >> "$out_hh"
sed -n -E "/.*static const int/{p;}" "$in_h" | sed -E "s/.*(const int [A-Za-z_]*).*$/extern \1;/g" >> "$out_hh"
echo "" >> "$out_hh"

